# Generated by go2rpm
%bcond_without check

# https://github.com/linuxdeepin/go-x11-client
%global goipath         github.com/linuxdeepin/go-x11-client
Version:                0.6.0
%global tag             %{version}

%gometa

%global goname          golang-github-linuxdeepin-go-x11-client
%global godevelname     golang-github-linuxdeepin-go-x11-client-devel

%global common_description %{expand:
A X11 client Go bindings for Deepin Desktop Environment.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README debian/changelog

Name:           %{goname}
Release:        1%{?dist}
Summary:        X11 client Go bindings for Deepin Desktop Environment

License:        GPLv3
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/text/encoding/charmap)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(gopkg.in/check.v1)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
rm -rf tools/gen

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Tue Jun 04 18:18:00 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0.4.1-1
- Release 0.4.1

* Tue Feb 26 2019 mosquito <sensor.wen@gmail.com> - 0-0.10.20190226git460ffe2
- Update to 460ffe2

* Fri Feb 01 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.9.git8411934
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Mon Nov 12 2018 mosquito <sensor.wen@gmail.com> - 0-0.8.20181112git8411934
- Update to 8411934
- New X connect failed: WindowError
  https://github.com/linuxdeepin/developer-center/issues/590

* Sun Nov  4 2018 mosquito <sensor.wen@gmail.com> - 0-0.7.20181104git0354113
- Update to 0354113

* Sat Aug 25 2018 mosquito <sensor.wen@gmail.com> - 0-0.6.git71929bb
- Update to 71929bb

* Fri Jul 27 2018 mosquito <sensor.wen@gmail.com> - 0-0.5.git70dbb86
- Update to 70dbb86

* Fri Jul 13 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.4.gita10a839
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Wed Feb 07 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.3.gita10a839
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Sat Oct 14 2017 mosquito <sensor.wen@gmail.com> - 0-0.2.gita10a839
- Update to a10a839

* Sun Aug 27 2017 mosquito <sensor.wen@gmail.com> - 0-0.1.git67aca0b
- Initial package build
