# Generated by go2rpm 1
%bcond_without check

# https://github.com/kelvins/sunrisesunset
%global goipath         github.com/kelvins/sunrisesunset
Version:                1.0

%gometa

%global common_description %{expand:
:sunrise: Go package that provides the sunrise and sunset equation.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        :sunrise: Go package that provides the sunrise and sunset equation

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed May 06 23:59:23 CST 2020 Robin Lee <robinlee.sysu@gmail.com> - 1.0-1
- Initial package

