# Generated by go2rpm
%bcond_without check

# https://github.com/linuxdeepin/go-dbus-factory
%global goipath         github.com/linuxdeepin/go-dbus-factory
Version:                1.6.4
%global tag             %{version}

%gometa

%global common_description %{expand:
Go DBus factory for Deepin Desktop Environment.}

%global godocs          CHANGELOG.md README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go DBus factory for Deepin Desktop Environment

License:        GPLv3
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(pkg.deepin.io/lib/dbus1)
BuildRequires:  golang(pkg.deepin.io/lib/dbusutil)
BuildRequires:  golang(pkg.deepin.io/lib/dbusutil/proxy)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.9.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Mon Aug  5 2019 Robin Lee <cheeselee@fedoraproject.org> - 0.9.0-1
- Release 0.9.0

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Tue Jun 04 18:32:05 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0.8.0-1
- Release 0.8.0

* Fri Feb 01 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.0-2.git375d4e7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Sat Dec 15 2018 mosquito <sensor.wen@gmail.com> - 0.2.0-1.20181215git375d4e7
- Update to 375d4e7

* Thu Nov 29 2018 mosquito <sensor.wen@gmail.com> - 0.1.0-1.20181129git19d6db1
- Update to 19d6db1

* Fri Nov  9 2018 mosquito <sensor.wen@gmail.com> - 0.0.7.1-1.20181109git0bb7f20
- Update to 0bb7f20

* Fri Aug 10 2018 mosquito <sensor.wen@gmail.com> - 0.0.7-1.20180827gite843337
- Update to e843337

* Thu Aug  2 2018 mosquito <sensor.wen@gmail.com> - 0-0.2.git6184b97
- Update to 6184b97

* Fri Jul 27 2018 mosquito <sensor.wen@gmail.com> - 0-0.1.git67aca0b
- Initial package build
