# Generated by go2rpm 1
%bcond_without check

# https://github.com/rickb777/date
%global goipath         github.com/rickb777/date
Version:                1.12.4

%gometa

%global common_description %{expand:
A Go package for working with dates.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A Go package for working with dates

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/rickb777/plural)
BuildRequires:  golang(golang.org/x/text/language)
BuildRequires:  golang(golang.org/x/text/message)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in datetool; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Thu May 07 00:06:21 CST 2020 Robin Lee <robinlee.sysu@gmail.com> - 1.12.4-1
- Initial package

