# Generated by go2rpm 1
%bcond_without check

# https://github.com/teambition/rrule-go
%global goipath         github.com/teambition/rrule-go
Version:                1.5.0

%gometa

%global common_description %{expand:
Go library for working with recurrence rules for calendar dates.}

%global golicenses      LICENSE
%global godocs          example README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go library for working with recurrence rules for calendar dates

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu May 07 00:04:17 CST 2020 Robin Lee <robinlee.sysu@gmail.com> - 1.5.0-1
- Initial package

