# Generated by go2rpm 1
%bcond_without check

# https://github.com/mozillazg/go-pinyin
%global goipath         github.com/mozillazg/go-pinyin
Version:                0.17.0

%gometa

%global common_description %{expand:
汉字转拼音.}

%global golicenses      LICENSE _tools/pinyin-data/LICENSE
%global godocs          README.md CHANGELOG.md _tools/pinyin-data/GBK_PUA.txt\\\
                        _tools/pinyin-data/kMandarin.txt _tools/pinyin-\\\
                        data/zdic.txt _tools/pinyin-data/kHanyuPinlu.txt\\\
                        _tools/pinyin-data/README.md _tools/pinyin-\\\
                        data/kMandarin_8105.txt _tools/pinyin-\\\
                        data/CHANGELOG.md _tools/pinyin-data/kXHC1983.txt\\\
                        _tools/pinyin-data/kHanyuPinyin.txt _tools/pinyin-\\\
                        data/overwrite.txt _tools/pinyin-data/pinyin.txt\\\
                        _tools/pinyin-data/nonCJKUI.txt _tools/pinyin-\\\
                        data/kMandarin_overwrite.txt _tools/pinyin-\\\
                        data/unihan/kMandarin.txt _tools/pinyin-\\\
                        data/unihan/kHanyuPinlu.txt _tools/pinyin-\\\
                        data/unihan/README.md _tools/pinyin-\\\
                        data/unihan/kXHC1983.txt _tools/pinyin-\\\
                        data/unihan/kHanyuPinyin.txt _tools/pinyin-\\\
                        data/tools/china-8105-06062014.txt _tools/pinyin-\\\
                        data/tools/requirements.txt

Name:           %{goname}
Release:        1%{?dist}
Summary:        汉字转拼音

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/mattn/go-isatty)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
for cmd in _tools; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md CHANGELOG.md
%{_bindir}/*


%gopkgfiles

%changelog
* Sun May 03 11:07:33 CST 2020 Robin Lee <cheeselee@fedoraproject.org> - 0.17.0-1
- Initial package

